modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Kamefrede/jnemloadscreen"
license="https://github.com/Kamefrede/jnemloadscreen/LICENSE"

[[mods]]
modId="jnemloadscreen"
displayName="JNEM Loadscreen"
version="2.0.0.0"
authors="Kamefrede, Boomflex"
description='''
Just Not Enough Mods 3 Loadscreen Mod!
'''
[[dependencies.jnemloadscreen]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.5,)"
    ordering="AFTER"
    side="BOTH"